language: python

python:
  - "2.7"
  - "3.4"

install: false

branches:
  except:
    - develop

before_script:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install python-fontforge -y

script: ./build.sh
